import type { Metadata } from "next";
import { Inter } from "@next/font/google"; // Import Inter font from Google
import "./globals.css";


// Load Inter font from Google Fonts
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // Optional CSS variable
  weight: "variable", // Add other weights if needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased bg-black`}
      >
        {children}
      </body>
    </html>
  );
}
